version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./back:/usr/src/app
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./database:/data
