version: '3.9'

services:
  back:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./back:/usr/src/app/back
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  front:
    build: ./front
    depends_on:
      - back
    ports:
      - "8080:80"